mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
spring:
  datasource:
    url: jdbc:h2:mem:mydb2
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
    show-sql: true 
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
      platform: h2
  
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    default-model-rendering: model 